#!/bin/sh
# Emit zsh-syntax-highlighting styles whose colors come from the LIVE
# wallpaper palette, computed at wallpaper-sync time (shell startup stays
# instant — shells just source the output file).
#
# Rule: nonexistent commands (unknown-token) render in the COMPLEMENTARY hue
# of the wallpaper accent (hue + 180°) so a wrong command visually opposes
# the warm accent/status colors instead of blending into the error red.
out="$HOME/.cache/zsh-wallpaper.zsh"

# Remove stale output when we can't compute (python absent / palette missing),
# so shells fall back to the static styles in ~/.zshrc_custom.
if ! command -v python3 >/dev/null 2>&1; then
   rm -f "$out"
   exit 0
fi

python3 - "$out" <<'PY'
import colorsys, os, re, sys

out = sys.argv[1]
palette = os.path.expanduser('~/.config/wezterm/colors/matugen.lua')
try:
    txt = open(palette, encoding='utf-8').read()
except OSError:
    sys.exit(0)

m = re.search(r'^\s*primary\s*=\s*"#([0-9A-Fa-f]{6})"', txt, re.M)
if not m:
    sys.exit(0)

hexs = m.group(1)
r, g, b = (int(hexs[i:i + 2], 16) / 255 for i in (0, 2, 4))

# A near-gray accent has no meaningful hue -> leave the static fallback.
if max(r, g, b) - min(r, g, b) < 0.10:
    sys.exit(0)

h, l, s = colorsys.rgb_to_hls(r, g, b)
h = (h + 0.5) % 1.0  # complementary
r, g, b = colorsys.hls_to_rgb(h, l, s)


def ch(v):
    return '%02x' % round(max(0.0, min(1.0, v)) * 255)


comp = '#%s%s%s' % (ch(r), ch(g), ch(b))
with open(out, 'w', encoding='utf-8') as f:
    f.write('# generated by zsh-highlight-sync.sh on wallpaper sync\n')
    f.write('ZSH_HIGHLIGHT_STYLES[unknown-token]="fg=%s,bold"\n' % comp)
PY
exit 0
