git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never

gui:
  showRandomTip: false
  border: rounded
  theme:
    activeBorderColor:
      - blue
      - bold
  sidePanelWidth: 0.33
  expandFocusedSidePanel: true

quitOnTopLevelReturn: true
disableStartupPopups: true
notARepository: quit
