-- Generated by matugen from the current wallpaper. Do not edit.
return {
   foreground = "#ede0d4",
   background = "#18120b",
   primary = "#f3bd6e",
   secondary = "#b7cea2",
   tertiary = "#b7cea2",
   success = "#7f560f",
   error = "#ffb4ab",
   surface0 = "#251f17",
   surface1 = "#2f2921",
   surface2 = "#3b342b",
   outline = "#9b8f80",
}
