-- Generated by matugen from the current wallpaper. Do not edit.
return {
   foreground = "#f1dedc",
   background = "#1a1110",
   primary = "#ffb3ac",
   secondary = "#e1c38c",
   tertiary = "#e1c38c",
   success = "#904a45",
   error = "#ffb4ab",
   surface0 = "#271d1c",
   surface1 = "#322826",
   surface2 = "#3d3231",
   outline = "#a08c8a",
}
